-- WatchVerdict — all pending migrations, safe to paste & run once in the
-- Supabase SQL Editor. Every statement is idempotent (IF NOT EXISTS /
-- DROP POLICY IF EXISTS), so re-running is harmless if some are already applied.
-- NOTE: Live Court v2 (0014) needs the base 0004_court.sql applied first.

-- ====================================================================
-- 0014_court_search.sql
-- ====================================================================
-- WatchVerdict — Live Court v2: each person searches the real titles THEY want
-- to watch (a wishlist), and the judge ranks 3 that best fit the whole group.
--
-- Adds per-participant `picks` (their searched titles) and a room-level
-- `seen_keys` ledger so "show 3 more" and per-title vetoes never repeat a title.
-- Everything still flows through SECURITY DEFINER RPCs so guests can play.

alter table public.court_participants
  add column if not exists picks jsonb not null default '[]'::jsonb;

alter table public.court_rooms
  add column if not exists seen_keys text[] not null default '{}';

-- A participant sets/updates their wishlist (the titles they searched for).
-- Only allowed while the room is still in the lobby.
create or replace function public.court_set_picks(
  p_code text, p_participant uuid, p_picks jsonb
)
returns void
language plpgsql security definer set search_path = public as $$
declare v_room public.court_rooms;
begin
  select * into v_room from public.court_rooms where code = p_code;
  if not found then raise exception 'Room not found'; end if;
  if v_room.status <> 'lobby' then raise exception 'Court already started'; end if;
  if jsonb_typeof(coalesce(p_picks, '[]'::jsonb)) <> 'array' then
    raise exception 'picks must be an array';
  end if;
  -- Cap at 8 picks per person so the pool stays sane.
  update public.court_participants
    set picks = (
      select coalesce(jsonb_agg(elem), '[]'::jsonb)
      from (select elem from jsonb_array_elements(coalesce(p_picks, '[]'::jsonb)) elem limit 8) s
    )
    where id = p_participant and room_id = v_room.id;
end; $$;

-- Public room snapshot for polling. Now also reports each participant's pick
-- count so the lobby can show who's ready. Individual votes stay hidden until
-- the verdict, exactly as before.
create or replace function public.court_state(p_code text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_room public.court_rooms; v_parts jsonb;
begin
  select * into v_room from public.court_rooms where code = p_code;
  if not found then return null; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', cp.id,
    'name', cp.name,
    'voted', cp.voted,
    'pickCount', coalesce(jsonb_array_length(cp.picks), 0),
    'vetoIndex', case when v_room.status = 'verdict' then cp.veto_index else null end,
    'vetoReason', case when v_room.status = 'verdict' then cp.veto_reason else null end
  ) order by cp.created_at), '[]'::jsonb) into v_parts
  from public.court_participants cp where cp.room_id = v_room.id;
  return jsonb_build_object(
    'status', v_room.status,
    'mediaType', v_room.media_type,
    'finalists', v_room.finalists,
    'participants', v_parts
  );
end; $$;

grant execute on function public.court_set_picks(text, uuid, jsonb) to anon, authenticated;


-- ====================================================================
-- 0015_outbound_clicks.sql
-- ====================================================================
-- WatchVerdict — outbound affiliate/provider click log (attribution funnel).
-- Written server-side by /api/out via the service role only; no client access.
-- Optional: /api/out degrades to console logging when this table is absent.

create table if not exists public.outbound_clicks (
  id         bigint generated by default as identity primary key,
  provider   text,
  type       text,        -- flatrate / rent / buy / free / ads
  media_type text,        -- movie / tv
  tmdb_id    bigint,
  host       text,        -- destination hostname
  referer    text,
  created_at timestamptz not null default now()
);

create index if not exists idx_outbound_clicks_created on public.outbound_clicks(created_at desc);
create index if not exists idx_outbound_clicks_provider on public.outbound_clicks(provider);

-- Locked down: only the service role (server) touches it. No policies = no
-- anon/authenticated access under RLS.
alter table public.outbound_clicks enable row level security;


-- ====================================================================
-- 0016_entitlements.sql
-- ====================================================================
-- WatchVerdict — Pro entitlements. Processor-agnostic: a row here means the
-- user has Pro. A payment processor (Stripe/Lemon Squeezy/…) writes it via the
-- service role from its webhook; the app only ever READS it. Until a processor
-- is wired, Pro can be granted manually (admin) — the gate is fully functional.

create table if not exists public.entitlements (
  user_id             uuid primary key references auth.users(id) on delete cascade,
  pro                 boolean not null default false,
  source              text,                          -- 'stripe' | 'manual' | 'promo' | …
  current_period_end  timestamptz,                   -- when the current paid period lapses (null = no expiry)
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists entitlements_updated_at on public.entitlements;
create trigger entitlements_updated_at
  before update on public.entitlements
  for each row execute function public.set_updated_at();

alter table public.entitlements enable row level security;

-- Users may READ their own entitlement (so the client can reflect Pro state).
-- Writes are service-role only (processor webhook / admin) — no write policy.
drop policy if exists entitlements_select_own on public.entitlements;
create policy entitlements_select_own on public.entitlements
  for select using (auth.uid() = user_id);


-- ====================================================================
-- 0017_title_dimensions.sql
-- ====================================================================
-- WatchVerdict — AI content fingerprint. Every title gets classified once across
-- ~18 interpretable taste axes (pacing, darkness, gore, dialogue, …). This is
-- global, user-agnostic content metadata: computed by the server (service role),
-- readable by everyone. Cached forever — a title's fingerprint doesn't change.

create table if not exists public.title_dimensions (
  tmdb_id    bigint not null,
  media_type text not null check (media_type in ('movie','tv')),
  dims       jsonb not null,     -- { pacing:0..100, darkness:0..100, ... }
  model      text,               -- classifier model id, for future re-scoring
  created_at timestamptz not null default now(),
  primary key (tmdb_id, media_type)
);

alter table public.title_dimensions enable row level security;

-- Content metadata, not user data: any signed-in user may read it. Writes are
-- service-role only (the classifier), so no write policy is defined.
drop policy if exists title_dimensions_select on public.title_dimensions;
create policy title_dimensions_select on public.title_dimensions
  for select using (true);


