import { describe, it, expect } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { DIMENSION_KEYS } from '@/lib/scoring/dimensions';
import type { TitleDimensions } from '@/lib/scoring/dimensions';
import { deriveDna } from './engine';
import { rankWithPreference, preferenceConfidence, type RankInput } from './rank';
import { explainTitle } from './explain';
import { caseUpdate } from './caseUpdate';
import type { PreferenceEvent } from './types';

/**
 * Generates docs/dna-rank-report.md — a BEFORE/AFTER ranking report over a fixed
 * candidate set, using the SAME production nudge (`rankWithPreference`) that
 * `rankByDna` applies. Objective scores are supplied (live scoring needs
 * TMDB/OpenAI), so this isolates the preference contribution. Also asserts the
 * round materially reranks.
 */
function dims(over: Record<string, number>): TitleDimensions {
  const d: TitleDimensions = {};
  for (const k of DIMENSION_KEYS) d[k] = 50;
  return { ...d, ...over };
}

interface Title extends RankInput { name: string }
const CANDIDATES: Title[] = [
  { id: 'paddington', name: 'Paddington 2', objective: 88, genres: ['family', 'comedy'], dims: dims({ warmth: 90, humor: 82, darkness: 12, violence: 6, realism: 55 }) },
  { id: 'mare', name: 'Mare of Easttown', objective: 85, genres: ['crime', 'drama', 'mystery'], dims: dims({ realism: 90, pacing: 30, darkness: 78, character: 88, complexity: 70 }) },
  { id: 'zodiac', name: 'Zodiac', objective: 82, genres: ['crime', 'thriller', 'mystery'], dims: dims({ realism: 88, pacing: 58, darkness: 80, complexity: 72, violence: 60 }) },
  { id: 'conjuring', name: 'The Conjuring', objective: 78, genres: ['horror', 'supernatural'], dims: dims({ realism: 18, suspense: 88, darkness: 85 }) },
  { id: 'wednesday', name: 'Wednesday', objective: 76, genres: ['supernatural', 'mystery', 'comedy'], dims: dims({ realism: 28, humor: 62, darkness: 55 }) },
  { id: 'tenet', name: 'Tenet', objective: 74, genres: ['scifi', 'action'], dims: dims({ complexity: 95, realism: 38, pacing: 82, violence: 55 }) },
];

const ev = (over: Partial<PreferenceEvent>): PreferenceEvent => ({ id: Math.random().toString(36).slice(2), at: 0, titleId: 't', action: 'skip', ...over });
const many = (n: number, over: Partial<PreferenceEvent>) => Array.from({ length: n }, (_, i) => ev({ id: `${over.action}-${(over.genres ?? []).join('')}-${i}`, titleId: `x${i}`, ...over }));

// A round: loves grounded crime mysteries, rejects supernatural, tolerates dark.
const ROUND: PreferenceEvent[] = [
  ...many(4, { action: 'seen_liked', experienceGrade: 'loved', dims: dims({ realism: 85, darkness: 75, complexity: 65 }), genres: ['crime', 'mystery'] }),
  ...many(3, { action: 'unseen_not_interested', dims: dims({ realism: 20 }), genres: ['supernatural'] }),
];

function fmt(rows: ReturnType<typeof rankWithPreference>, byId: Map<string, Title>) {
  return rows.map((r, i) => `| ${i + 1} | ${byId.get(r.id)!.name} | ${r.objective} | ${r.nudge >= 0 ? '+' : ''}${r.nudge.toFixed(1)} | ${r.finalScore.toFixed(1)} |`).join('\n');
}

describe('DNA ranking before/after report', () => {
  it('materially reranks and writes the report', () => {
    const byId = new Map(CANDIDATES.map((c) => [c.id, c]));
    const empty = deriveDna([], 0);
    const after = deriveDna(ROUND, 0);

    const before = rankWithPreference(CANDIDATES, empty);
    const afterRanked = rankWithPreference(CANDIDATES, after);

    const beforeOrder = before.map((r) => r.id);
    const afterOrder = afterRanked.map((r) => r.id);
    const rankBefore = new Map(beforeOrder.map((id, i) => [id, i]));

    // Movement + reason per title.
    const moves = afterRanked.map((r, i) => {
      const from = rankBefore.get(r.id)!;
      const delta = from - i; // positive = moved up
      const ex = explainTitle({ dims: byId.get(r.id)!.dims, genres: byId.get(r.id)!.genres }, after);
      const why = r.nudge >= 0 ? (ex.reasons[0]?.text ?? 'matches your taste') : (ex.concerns[0]?.text ?? 'clashes with your taste');
      return { name: byId.get(r.id)!.name, from: from + 1, to: i + 1, delta, nudge: r.nudge, why };
    });

    const cu = caseUpdate(empty, after);
    const confBefore = Math.round(preferenceConfidence(empty) * 100);
    const confAfter = Math.round(preferenceConfidence(after) * 100);

    const doc = `# DNA Case — before/after ranking report

Generated by the production preference nudge (\`rankWithPreference\` → \`preferenceNudge\`,
the exact term \`rankByDna\` adds). Objective (Watchability) scores are held fixed at the
supplied values because live scoring needs TMDB/OpenAI; this isolates the DNA Case
contribution. Same candidate set before and after one Case Round.

## Ranking BEFORE the round (cold DNA — objective order)

| # | Title | Objective | DNA nudge | Final |
|---|-------|-----------|-----------|-------|
${fmt(before, byId)}

Preference confidence: **${confBefore}%**

## Evidence submitted this round

- 4× **Watched — Loved** grounded crime/mystery titles (realism↑, dark-tolerant, some complexity)
- 3× **Haven't seen — Not for Me** supernatural titles

## Trait changes (New Evidence + confidence gains)

${cu.newEvidence.map((s) => `- ${s}`).join('\n') || '- (none crossed the resolve threshold)'}

Confidence improved: ${cu.confidenceImproved.map((c) => `${c.label} +${c.deltaPct}%`).join(', ') || '(n/a)'}

## Ranking AFTER the round

| # | Title | Objective | DNA nudge | Final |
|---|-------|-----------|-----------|-------|
${fmt(afterRanked, byId)}

Preference confidence: **${confAfter}%**

## Why each title moved

| Title | Before → After | Δ | Nudge | Reason |
|-------|----------------|---|-------|--------|
${moves.map((m) => `| ${m.name} | ${m.from} → ${m.to} | ${m.delta > 0 ? '▲' + m.delta : m.delta < 0 ? '▼' + Math.abs(m.delta) : '—'} | ${m.nudge >= 0 ? '+' : ''}${m.nudge.toFixed(1)} | ${m.why} |`).join('\n')}

_Nudge is bounded to ±10 (PREF_NUDGE_MAX); the deterministic Watchability score stays authoritative._
`;

    const dir = path.join(process.cwd(), 'docs');
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, 'dna-rank-report.md'), doc, 'utf8');

    // Materiality: order changed; grounded crime nudged up, supernatural down.
    expect(afterOrder).not.toEqual(beforeOrder);
    expect(afterOrder.indexOf('conjuring')).toBeGreaterThan(beforeOrder.indexOf('conjuring'));
    const nudgeOf = (id: string) => afterRanked.find((r) => r.id === id)!.nudge;
    expect(nudgeOf('zodiac')).toBeGreaterThan(0);
    expect(nudgeOf('mare')).toBeGreaterThan(0);
    expect(nudgeOf('conjuring')).toBeLessThan(0); // pure supernatural sinks
    // A grounded title ends up ranked above a supernatural one it did not clearly lead before.
    expect(afterOrder.indexOf('zodiac')).toBeLessThan(afterOrder.indexOf('conjuring'));
    expect(confAfter).toBeGreaterThan(confBefore);
  });
});
