-- WatchVerdict — outbound affiliate/provider click log (attribution funnel).
-- Written server-side by /api/out via the service role only; no client access.
-- Optional: /api/out degrades to console logging when this table is absent.

create table if not exists public.outbound_clicks (
  id         bigint generated by default as identity primary key,
  provider   text,
  type       text,        -- flatrate / rent / buy / free / ads
  media_type text,        -- movie / tv
  tmdb_id    bigint,
  host       text,        -- destination hostname
  referer    text,
  created_at timestamptz not null default now()
);

create index if not exists idx_outbound_clicks_created on public.outbound_clicks(created_at desc);
create index if not exists idx_outbound_clicks_provider on public.outbound_clicks(provider);

-- Locked down: only the service role (server) touches it. No policies = no
-- anon/authenticated access under RLS.
alter table public.outbound_clicks enable row level security;
