-- 0023_preference_dna.sql
-- THE DNA CASE persistence. An append-only evidence log is the source of truth;
-- everything else (trait confidence, DNA-strength history) is a derivable cache.
-- Fully idempotent. RLS: a user can only ever touch their own rows.

-- ---------------------------------------------------------------------------
-- preference_events — every reaction, with full provenance. Client generates a
-- stable id so re-sends dedup (insert on conflict do nothing). Undo is a SOFT
-- delete (undone_at) so history is never destroyed — reads filter it out.
create table if not exists public.preference_events (
  id             text primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  title_id       text not null,                 -- e.g. "movie:603"
  tmdb_id        bigint,
  media_type     text check (media_type in ('movie','tv')),
  action         text not null,                 -- seen_liked | unseen_interested | skip | ...
  experience_grade text,                         -- loved..dnf
  attraction_grade text,                         -- must_watch..absolutely_not
  discovery_grade  text,
  reasons        text[] not null default '{}',
  corrections    jsonb  not null default '[]',   -- [{key,target}]
  dims           jsonb,                           -- title fingerprint snapshot (provenance)
  genres         text[] not null default '{}',
  people         text[] not null default '{}',
  dwell_ms       integer,                         -- quality signal
  familiarity    real,
  source         text,                            -- onboarding | round | home | ...
  round_id       text,
  mood           boolean not null default false,
  locale         text,
  device         text,
  event_at       timestamptz not null default now(),  -- when the user acted (mood decay)
  undone_at      timestamptz,                          -- soft-delete for Undo (audit trail kept)
  created_at     timestamptz not null default now()
);
create index if not exists idx_pref_events_user on public.preference_events(user_id, event_at desc);
create index if not exists idx_pref_events_user_live on public.preference_events(user_id) where undone_at is null;

alter table public.preference_events enable row level security;
drop policy if exists pref_events_select_own on public.preference_events;
create policy pref_events_select_own on public.preference_events for select using (user_id = auth.uid());
drop policy if exists pref_events_insert_own on public.preference_events;
create policy pref_events_insert_own on public.preference_events for insert with check (user_id = auth.uid());
drop policy if exists pref_events_update_own on public.preference_events;
create policy pref_events_update_own on public.preference_events for update using (user_id = auth.uid());
drop policy if exists pref_events_delete_own on public.preference_events;
create policy pref_events_delete_own on public.preference_events for delete using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- trait_confidence — derivable per-(user, channel, trait) cache, so reads don't
-- re-fold the whole log every request. Source of truth remains the event log.
create table if not exists public.trait_confidence (
  user_id     uuid not null references auth.users(id) on delete cascade,
  channel     text not null,       -- experience | attraction | discovery
  trait_kind  text not null,       -- dim | genre | person | novelty
  trait_key   text not null,
  pref        real not null default 50,
  evidence    real not null default 0,
  confidence  real not null default 0,
  updated_at  timestamptz not null default now(),
  primary key (user_id, channel, trait_kind, trait_key)
);
alter table public.trait_confidence enable row level security;
drop policy if exists trait_conf_select_own on public.trait_confidence;
create policy trait_conf_select_own on public.trait_confidence for select using (user_id = auth.uid());
drop policy if exists trait_conf_insert_own on public.trait_confidence;
create policy trait_conf_insert_own on public.trait_confidence for insert with check (user_id = auth.uid());
drop policy if exists trait_conf_update_own on public.trait_confidence;
create policy trait_conf_update_own on public.trait_confidence for update using (user_id = auth.uid());
drop policy if exists trait_conf_delete_own on public.trait_confidence;
create policy trait_conf_delete_own on public.trait_confidence for delete using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- recommendation_outcomes — did our prediction hold? Feeds Outcome Calibration
-- and Prediction Accuracy (gated to ≥10 samples in code).
create table if not exists public.recommendation_outcomes (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  tmdb_id       bigint not null,
  media_type    text not null check (media_type in ('movie','tv')),
  predicted     integer,             -- our score at recommendation time
  outcome       text,                -- watched_liked | dnf | not_for_me | ...
  correct       boolean,
  session_id    text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_rec_outcomes_user on public.recommendation_outcomes(user_id, created_at desc);
alter table public.recommendation_outcomes enable row level security;
drop policy if exists rec_outcomes_select_own on public.recommendation_outcomes;
create policy rec_outcomes_select_own on public.recommendation_outcomes for select using (user_id = auth.uid());
drop policy if exists rec_outcomes_insert_own on public.recommendation_outcomes;
create policy rec_outcomes_insert_own on public.recommendation_outcomes for insert with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- dna_strength_history — a point per recompute, so "your DNA got stronger" is
-- backed by real history.
create table if not exists public.dna_strength_history (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  developed   integer not null,
  categories  jsonb,
  round_id    text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_dna_strength_user on public.dna_strength_history(user_id, created_at desc);
alter table public.dna_strength_history enable row level security;
drop policy if exists dna_strength_select_own on public.dna_strength_history;
create policy dna_strength_select_own on public.dna_strength_history for select using (user_id = auth.uid());
drop policy if exists dna_strength_insert_own on public.dna_strength_history;
create policy dna_strength_insert_own on public.dna_strength_history for insert with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- case_rounds + case_round_items — the sessions and the titles they examined.
create table if not exists public.case_rounds (
  id           text primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  question_id  text,
  size         text,               -- quick | standard | deep
  status       text not null default 'active',  -- active | completed | abandoned
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists idx_case_rounds_user on public.case_rounds(user_id, created_at desc);
alter table public.case_rounds enable row level security;
drop policy if exists case_rounds_select_own on public.case_rounds;
create policy case_rounds_select_own on public.case_rounds for select using (user_id = auth.uid());
drop policy if exists case_rounds_insert_own on public.case_rounds;
create policy case_rounds_insert_own on public.case_rounds for insert with check (user_id = auth.uid());
drop policy if exists case_rounds_update_own on public.case_rounds;
create policy case_rounds_update_own on public.case_rounds for update using (user_id = auth.uid());

create table if not exists public.case_round_items (
  round_id    text not null references public.case_rounds(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  title_id    text not null,
  media_type  text,
  position    integer not null default 0,
  primary key (round_id, title_id)
);
alter table public.case_round_items enable row level security;
drop policy if exists case_items_select_own on public.case_round_items;
create policy case_items_select_own on public.case_round_items for select using (user_id = auth.uid());
drop policy if exists case_items_insert_own on public.case_round_items;
create policy case_items_insert_own on public.case_round_items for insert with check (user_id = auth.uid());
drop policy if exists case_items_delete_own on public.case_round_items;
create policy case_items_delete_own on public.case_round_items for delete using (user_id = auth.uid());
