-- 0024_growth_os.sql
-- Founder Growth Command Center (/growth-os) persistence. Owner-only data: a
-- lightweight outreach CRM, campaigns, tracked links + click log, and early-user
-- feedback. Fully idempotent. RLS: a user can only ever touch their OWN rows;
-- the /growth-os route is additionally gated to ADMIN_EMAILS in the app.

-- ── Prospects (outreach CRM) ────────────────────────────────────────────────
create table if not exists public.growth_prospects (
  id            uuid primary key default gen_random_uuid(),
  owner_id      uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  category      text,                       -- creator | community | newsletter | podcast | friend | partner | ...
  platform      text,
  audience_size integer,
  contact       text,
  relevance     integer,                    -- 1..5
  status        text not null default 'to_contact', -- to_contact | contacted | replied | activated | passed
  last_contact  date,
  next_follow_up date,
  message_used  text,
  response      text,
  attributed_signups integer not null default 0,
  activated_users    integer not null default 0,
  referred_users     integer not null default 0,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_growth_prospects_owner on public.growth_prospects(owner_id, next_follow_up);
alter table public.growth_prospects enable row level security;
drop policy if exists growth_prospects_own on public.growth_prospects;
create policy growth_prospects_own on public.growth_prospects for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- ── Campaigns ───────────────────────────────────────────────────────────────
create table if not exists public.growth_campaigns (
  id            uuid primary key default gen_random_uuid(),
  owner_id      uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  audience      text,
  value_prop    text,
  headline      text,
  cta           text,
  channel       text,
  destination   text not null default '/app/quiz',
  tracking_code text,
  starts_on     date,
  ends_on       date,
  spend_usd     numeric(10,2) not null default 0,
  status        text not null default 'draft', -- draft | live | paused | done
  created_at    timestamptz not null default now()
);
create index if not exists idx_growth_campaigns_owner on public.growth_campaigns(owner_id, created_at desc);
alter table public.growth_campaigns enable row level security;
drop policy if exists growth_campaigns_own on public.growth_campaigns;
create policy growth_campaigns_own on public.growth_campaigns for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- ── Tracked links (attribution) ─────────────────────────────────────────────
create table if not exists public.growth_links (
  id            uuid primary key default gen_random_uuid(),
  owner_id      uuid not null references auth.users(id) on delete cascade,
  campaign_id   uuid references public.growth_campaigns(id) on delete set null,
  slug          text not null unique,        -- /go/<slug>
  label         text not null,
  destination   text not null default '/app/quiz',
  source        text not null,               -- utm_source
  medium        text,                        -- utm_medium
  campaign      text,                        -- utm_campaign
  content       text,                        -- utm_content (post/message variant)
  ref_user      text,                        -- referring user id (referral links)
  click_count   integer not null default 0,
  created_at    timestamptz not null default now()
);
create index if not exists idx_growth_links_owner on public.growth_links(owner_id, created_at desc);
alter table public.growth_links enable row level security;
drop policy if exists growth_links_own on public.growth_links;
create policy growth_links_own on public.growth_links for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- ── Click log (append-only; written only by the SECURITY DEFINER RPC) ────────
create table if not exists public.growth_link_clicks (
  id         bigint generated by default as identity primary key,
  link_id    uuid not null references public.growth_links(id) on delete cascade,
  clicked_at timestamptz not null default now(),
  referer    text,
  ua         text
);
create index if not exists idx_growth_link_clicks_link on public.growth_link_clicks(link_id, clicked_at desc);
alter table public.growth_link_clicks enable row level security;
-- Owner can read clicks for their own links (join through growth_links).
drop policy if exists growth_link_clicks_owner_read on public.growth_link_clicks;
create policy growth_link_clicks_owner_read on public.growth_link_clicks for select using (
  exists (select 1 from public.growth_links l where l.id = link_id and l.owner_id = auth.uid())
);

-- Public link resolution + click logging, atomic, via SECURITY DEFINER so the
-- /go/<slug> redirect works for anonymous visitors without a broad anon policy.
create or replace function public.growth_click(p_slug text, p_referer text, p_ua text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare v_link public.growth_links;
begin
  select * into v_link from public.growth_links where slug = p_slug;
  if not found then return null; end if;
  insert into public.growth_link_clicks(link_id, referer, ua) values (v_link.id, left(p_referer, 300), left(p_ua, 300));
  update public.growth_links set click_count = click_count + 1 where id = v_link.id;
  return v_link.destination;
end; $$;
grant execute on function public.growth_click(text, text, text) to anon, authenticated;

-- ── Early-user feedback ─────────────────────────────────────────────────────
create table if not exists public.growth_feedback (
  id             uuid primary key default gen_random_uuid(),
  owner_id       uuid not null references auth.users(id) on delete cascade,
  subject        text,                       -- who (name/email/handle)
  source         text,                       -- acquisition source
  activation     text,                       -- not_started | onboarding | dna_done | active | invited
  first_impression text,
  confusion      text,
  favorite       text,
  missing        text,
  return_likelihood integer,                 -- 1..5
  invite_likelihood integer,                 -- 1..5
  quote          text,
  follow_up_needed boolean not null default false,
  notes          text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_growth_feedback_owner on public.growth_feedback(owner_id, created_at desc);
alter table public.growth_feedback enable row level security;
drop policy if exists growth_feedback_own on public.growth_feedback;
create policy growth_feedback_own on public.growth_feedback for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- ── Owner settings (stage override, milestone target date) ──────────────────
create table if not exists public.growth_settings (
  owner_id       uuid primary key references auth.users(id) on delete cascade,
  stage_override text,                       -- null = auto | stage1 | stage2 | stage3 | scale
  milestone_target_date date,
  updated_at     timestamptz not null default now()
);
alter table public.growth_settings enable row level security;
drop policy if exists growth_settings_own on public.growth_settings;
create policy growth_settings_own on public.growth_settings for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
