-- 0024_reco_validation.sql
-- Recommendation VALIDATION store. Every recommendation shown is logged as an
-- impression (with the DNA snapshot, algorithm version, predicted score,
-- confidence, and reasoning that produced it). Outcomes link back so we can
-- measure accuracy + calibration over time and A/B-compare algorithms.
-- Fully idempotent. RLS: a user can only ever touch their own rows.

create table if not exists public.recommendation_impressions (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  tmdb_id      bigint not null,
  media_type   text not null check (media_type in ('movie','tv')),
  surface      text,                       -- home | watch | title | ...
  algo_version text not null,              -- e.g. 'reco-1.0.0'
  predicted    integer,                    -- our 0..100 match score at show time
  confidence   text,                       -- low | medium | high
  reasoning    jsonb,                      -- factors used (why we recommended it)
  dna_snapshot jsonb,                      -- the DNA used to generate it (provenance)
  genres       text[] not null default '{}',
  platform     text,
  cohort       text,                       -- new | experienced
  session_id   text,
  shown_at     timestamptz not null default now()
);
create index if not exists idx_reco_impr_user on public.recommendation_impressions(user_id, shown_at desc);
create index if not exists idx_reco_impr_title on public.recommendation_impressions(user_id, tmdb_id, media_type);
create index if not exists idx_reco_impr_algo on public.recommendation_impressions(algo_version);

alter table public.recommendation_impressions enable row level security;
drop policy if exists reco_impr_select_own on public.recommendation_impressions;
create policy reco_impr_select_own on public.recommendation_impressions for select using (user_id = auth.uid());
drop policy if exists reco_impr_insert_own on public.recommendation_impressions;
create policy reco_impr_insert_own on public.recommendation_impressions for insert with check (user_id = auth.uid());

-- Link outcomes back to impressions + carry the facets we slice accuracy by.
-- Guarded so this migration is independent of 0023's apply order.
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'recommendation_outcomes') then
    alter table public.recommendation_outcomes add column if not exists impression_id bigint;
    alter table public.recommendation_outcomes add column if not exists algo_version text;
    alter table public.recommendation_outcomes add column if not exists confidence text;
    alter table public.recommendation_outcomes add column if not exists kind text;   -- watched|saved|skipped|dismissed|corrected|rated_up|rated_down
    alter table public.recommendation_outcomes add column if not exists genres text[] default '{}';
    alter table public.recommendation_outcomes add column if not exists platform text;
    alter table public.recommendation_outcomes add column if not exists cohort text;
  end if;
end $$;
